//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public int EventType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Time { get; set; }
        public int Duration { get; set; }
        public int Repeats { get; set; }
        public int LastUserEdited { get; set; }
        public System.DateTime LastDateEdited { get; set; }
        public string AdditionalNotes { get; set; }
        public string Status { get; set; }
        public int Room { get; set; }
        public int Course { get; set; }
        public int Module { get; set; }
    }
}
