//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Repeats { get; set; }
        public Nullable<int> LastUserEdited { get; set; }
        public Nullable<System.DateTime> LastDateEdited { get; set; }
        public string AdditionalNotes { get; set; }
        public string Status { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Attendants { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Module { get; set; }
    }
}
