//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleEvent
    {
        public int EventModule { get; set; }
        public int EventId { get; set; }
        public int ModuleId { get; set; }
        public int CourseId { get; set; }
    }
}
