//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecycledId
    {
        public string TableName { get; set; }
        public int IdRecovered { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
