//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeatEvent
    {
        public int RepeatEventId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> RepeatType { get; set; }
        public Nullable<System.DateTime> WeekBeginning { get; set; }
        public Nullable<System.DateTime> WeekEnding { get; set; }
    }
}
