//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsId { get; set; }
        public string SettingName { get; set; }
        public string SettingDescription { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Creator { get; set; }
        public string Active { get; set; }
    }
}
