//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudentTitle { get; set; }
        public string StudentForename { get; set; }
        public string StudentSurname { get; set; }
        public string StudentEmail { get; set; }
        public int Course { get; set; }
        public int Year { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastActivity { get; set; }
        public string Password { get; set; }
    }
}
