//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimetableDatabase : DbContext
    {
        public TimetableDatabase()
            : base("name=TimetableDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.Configuration.LazyLoadingEnabled = false;
            throw new UnintentionalCodeFirstException();
          
        }
    
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventStatuss> EventStatusses { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<RecycledId> RecycledIds { get; set; }
        public DbSet<RepeatEvent> RepeatEvents { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomType> RoomTypes { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Time> Times { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<RepeatType> RepeatTypes { get; set; }
        public DbSet<CourseModule> CourseModules { get; set; }
        public DbSet<StaffEvent> StaffEvents { get; set; }
        public DbSet<StudentEvent> StudentEvents { get; set; }
    }
}
