//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserTitle { get; set; }
        public string UserForename { get; set; }
        public string UserSurname { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string CurrentlyLoggedIn { get; set; }
        public string Password { get; set; }
    }
}
